steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/opt/sap/mta.jar'
  neoDeploy:
    neoHome: '/opt/sap/neo-sdk/'
    neo:
      credentialsId: 'devops-docker-images-IT-cf'
      account: 's7am47zded'
      host: 'eu1.hana.ondemand.com'
