steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
      org: "b4de12bftrial"
      space: "dev"
      credentialsId: 'cfDeploy'

